import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Button, Card, Col, Row} from "antd";
import Link from "next/link";

export default function Home({jobs}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Job Portal</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/download.png"/>
            </Head>

            <Card className={styles.card} bordered={false}>
                <div className={styles.hcenter}>
                    <h1 className={`styles.title !k-mb-2`}>Job Portal</h1>
                    <div className={styles.button}>
                        <Button type={'primary'}>
                            <Link href={'/jobs'}>Go to Jobs Page</Link>
                        </Button>
                    </div>
                </div>
            </Card>
        </div>
    )
}
