import {useRouter} from "next/router";
import {Button, Card, Col, Divider, List, Row, Space, Tag} from "antd";
import {IoLocationSharp} from "react-icons/io5";
import {AiFillDollarCircle} from "react-icons/ai";
import {FiSend} from "react-icons/fi";
import {FaUserCog, FaUsers} from "react-icons/fa";
import {HiBadgeCheck} from "react-icons/hi";
import {BsFillBagCheckFill} from "react-icons/bs";
import image from "./assets/images/foxhub2.png"
import Image from 'next/image'
import styles from "../../styles/PublicJobDetailsPage.module.scss"
import Head from "next/head";
import PageHeader from "../../Components/PageHeader/PageHeader";
import {MdArrowBackIosNew} from "react-icons/md";
import Link from "next/link";
import axios from "../../Config/axios";
import {TbCurrencyTaka} from "react-icons/tb";
import {nFormatter, salary} from "../../helper/utils";

export async function getServerSideProps(context) {
    let param = context;
    let id = param?.query?.jobId
    const res = await axios.get(`https://seashell-app-yubac.ondigitalocean.app/api/public/hr/hiring/job-openings/${id}`)
    return {
        props: {
            jobDetails: res.data.results
        }
    }
}

const JobId = ({jobDetails}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>{jobDetails?.job_title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/download.png"/>
            </Head>
            <div className='page-header'>
                <div>
                    <Link href={`/jobs`} replace={true}>
                        <Button
                            className={'button'}
                            icon={<MdArrowBackIosNew className={'icon'} size={16}/>}>
                        </Button>
                    </Link>

                    <PageHeader title={'Job Details'}/>
                </div>
            </div>
            <Card bordered={false}>
                <Row gutter={[30, 15]} wrap>
                    <Col className="gutter-row" xs={24} sm={24} md={24} lg={14} xl={15} xxl={18}>
                        <Card className={styles.job_details}>
                            <div className={styles.job_details_header}>
                                <div className={styles.left_side}>
                                    <Tag className={styles.employment_type}
                                         color="rgb(231 231 231)">{jobDetails?.employment_type?.name}</Tag>
                                    <h1 className={styles.title}>{jobDetails?.job_title}</h1>
                                    <div className={styles.location_salary_section}>
                                        <div className={styles.location}>
                                            <IoLocationSharp className={'icon'} color={'#87d068'} size={22}/>
                                            <p>
                                                {jobDetails?.workplace?.address?.street_address}{", "}
                                                {jobDetails?.workplace?.address?.state_province}{", "}
                                                {jobDetails?.workplace?.address?.city}
                                            </p>
                                        </div>
                                        <div className={styles.salary}>
                                            {
                                                jobDetails?.salary_currency === "BDT" ?
                                                    <TbCurrencyTaka
                                                        className={'icon'}
                                                        color={'#87d068'}
                                                        size={22}/> :
                                                    <AiFillDollarCircle
                                                        className={'icon'}
                                                        color={'#87d068'}
                                                        size={22}/>
                                            }
                                            <p>
                                                {nFormatter(jobDetails?.min_salary)}{" "}-{" "}
                                                {nFormatter(jobDetails?.max_salary)} {salary(jobDetails?.paid_every)}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <Link href={`/applyjob/${jobDetails.id}`}>
                                        <Button
                                            className={styles.button_style}
                                            type={'primary'}
                                            icon={<FiSend className={styles.send} size={18}/>}
                                        >
                                            APPLY NOW
                                        </Button>
                                    </Link>
                                </div>
                            </div>

                            <Divider/>

                            <div className="skill_section">
                                <h2 className={'skills'}>Skills : </h2>
                                {jobDetails?.skills?.split(',').map((skill, index) => (
                                    <Space size={[0, 8]} wrap key={index}>
                                        <Tag color="#2db7f5">{skill}</Tag>
                                    </Space>
                                ))}
                            </div>
                            <div>
                                <h2>Job Description : </h2>
                                <div
                                    className={'description'}
                                    dangerouslySetInnerHTML={{__html: jobDetails?.description}}/>
                            </div>
                        </Card>
                    </Col>

                    <Col className="gutter-row" xs={24} sm={24} md={24} lg={10} xl={9} xxl={6}>
                        <Card className={styles.job_details_right_side}>
                            <div className={styles.verified}>
                                <HiBadgeCheck color="#87d068" size={20}/>
                                Verified Company
                            </div>

                            <div className={styles.company_info_details}>
                                <Image
                                    alt={'logo'}
                                    width={50}
                                    height={50}
                                    src={jobDetails?.banner?.url ? jobDetails?.banner?.url : image}
                                />
                                <div className={styles.location_name}>
                                    <p>Jakarta, Indonesia</p>
                                    <h4>FoxHUB Studios</h4>
                                </div>
                            </div>
                            <Divider/>
                            <List className={`company_info`}>
                                <List.Item>
                                    <FaUsers color="#87d068" className={styles.icon_space} size={18}/>
                                    <span>Size: 1,001 - 5,000 employees</span>
                                </List.Item>

                                <List.Item>
                                    <FaUserCog color="#87d068" className={styles.icon_space} size={18}/>
                                    <span>Any Experience Welcomed</span>
                                </List.Item>

                                <List.Item>
                                    <BsFillBagCheckFill color="#87d068" className={styles.icon_space} size={18}/>
                                    <span>Industry: Healthcare, Insurance</span>
                                </List.Item>

                            </List>
                        </Card>
                    </Col>
                </Row>
            </Card>
        </div>
    );
};

export default JobId;